using System.Text.Json;
using MCPforDalamud.McpServer;
using Dalamud.Game.ClientState.Objects.Types;
using Dalamud.Game.ClientState.Conditions;
using LuminaAction = Lumina.Excel.Sheets.Action;

namespace MCPforDalamud.Tools;

public static class ActionTools
{
    public static void Register(ToolRegistry registry)
    {
        registry.Register(new ToolDefinition { Name = "execute_action", Description = "执行技能/操作", InputSchema = JsonSerializer.SerializeToElement(new { type = "object", properties = new { actionId = new { type = "integer" }, actionName = new { type = "string" }, targetObjectId = new { type = "integer" } } }), Handler = args => { EnsureReady(); uint actionId = 0; ulong targetId = 0xE0000000; if (args?.TryGetProperty("actionId", out var idProp) == true) actionId = (uint)idProp.GetInt32(); if (args?.TryGetProperty("actionName", out var nameProp) == true) { var name = nameProp.GetString() ?? ""; var sheet = Service.DataManager.GetExcelSheet<LuminaAction>(); foreach (var row in sheet) { if (row.Name.ToString() == name) { actionId = row.RowId; break; } } if (actionId == 0) return new { error = string.Format("未找到技能: {0}", name) }; } if (args?.TryGetProperty("targetObjectId", out var tidProp) == true) targetId = (ulong)tidProp.GetInt64(); if (actionId == 0) return new { error = "请提供 actionId 或 actionName" }; unsafe { var am = FFXIVClientStructs.FFXIV.Client.Game.ActionManager.Instance(); var ok = am->UseAction(FFXIVClientStructs.FFXIV.Client.Game.ActionType.Action, actionId, targetId, 0, 0, 0, null); return new { actionId, success = ok }; } } });
        registry.Register(new ToolDefinition { Name = "use_general_action", Description = "执行通用操作", InputSchema = JsonSerializer.SerializeToElement(new { type = "object", properties = new { actionId = new { type = "integer" } }, required = new[] { "actionId" } }), Handler = args => { EnsureReady(); var aId = (uint)(args?.GetProperty("actionId").GetInt32() ?? 0); if (aId == 0) return new { error = "请提供 actionId" }; unsafe { var am = FFXIVClientStructs.FFXIV.Client.Game.ActionManager.Instance(); var ok = am->UseAction(FFXIVClientStructs.FFXIV.Client.Game.ActionType.GeneralAction, aId, 0xE0000000, 0, 0, 0, null); return new { actionId = aId, actionType = "GeneralAction", success = ok }; } } });
        registry.Register(new ToolDefinition { Name = "set_target", Description = "设置当前目标", InputSchema = JsonSerializer.SerializeToElement(new { type = "object", properties = new { targetObjectId = new { type = "integer" }, targetName = new { type = "string" } } }), Handler = args => { EnsureReady(); IGameObject? target = null; if (args?.TryGetProperty("targetObjectId", out var idProp) == true) target = Service.ObjectTable.SearchById((ulong)idProp.GetInt64()); if (target == null && args?.TryGetProperty("targetName", out var nm) == true) target = Service.ObjectTable.FirstOrDefault(o => o != null && o.Name.TextValue.Contains(nm.GetString() ?? "")); if (target == null) return new { error = "未找到目标" }; Service.TargetManager.Target = target; return new { success = true, targetName = target.Name.TextValue, gameObjectId = target.GameObjectId }; } });
        registry.Register(new ToolDefinition { Name = "set_focus_target", Description = "设置焦点目标", InputSchema = JsonSerializer.SerializeToElement(new { type = "object", properties = new { targetObjectId = new { type = "integer" }, targetName = new { type = "string" } } }), Handler = args => { EnsureReady(); IGameObject? target = null; if (args?.TryGetProperty("targetObjectId", out var idProp) == true) target = Service.ObjectTable.SearchById((ulong)idProp.GetInt64()); if (target == null && args?.TryGetProperty("targetName", out var nm) == true) target = Service.ObjectTable.FirstOrDefault(o => o != null && o.Name.TextValue.Contains(nm.GetString() ?? "")); if (target == null) { Service.TargetManager.FocusTarget = null; return new { success = true, cleared = true }; } Service.TargetManager.FocusTarget = target; return new { success = true, targetName = target.Name.TextValue, gameObjectId = target.GameObjectId }; } });
        registry.Register(new ToolDefinition { Name = "interact_with_target", Description = "与当前目标交互", Handler = _ => { EnsureReady(); var t = Service.TargetManager.Target; if (t == null) return new { error = "没有当前目标" }; unsafe { var ts = FFXIVClientStructs.FFXIV.Client.Game.Control.TargetSystem.Instance(); var go = (FFXIVClientStructs.FFXIV.Client.Game.Object.GameObject*)t.Address; var result = ts->InteractWithObject(go, false); return new { success = result != 0, targetName = t.Name.TextValue }; } } });
        registry.Register(new ToolDefinition { Name = "dismount", Description = "下坐骑", Handler = _ => { EnsureReady(); if (!Service.Condition[ConditionFlag.Mounted]) return new { note = "未骑乘" }; unsafe { var am = FFXIVClientStructs.FFXIV.Client.Game.ActionManager.Instance(); am->UseAction(FFXIVClientStructs.FFXIV.Client.Game.ActionType.GeneralAction, 23, 0xE0000000, 0, 0, 0, null); return new { success = true }; } } });
        registry.Register(new ToolDefinition { Name = "cancel_cast", Description = "取消当前施法", Handler = _ => { EnsureReady(); unsafe { var uiState = FFXIVClientStructs.FFXIV.Client.Game.UI.UIState.Instance(); if (uiState != null) { uiState->Hotbar.CancelCast(); return new { success = true }; } return new { success = false, error = "UIState不可用" }; } } });
        registry.Register(new ToolDefinition { Name = "accept_raise", Description = "接受复活", Handler = _ => { EnsureReady(); unsafe { var am = FFXIVClientStructs.FFXIV.Client.Game.ActionManager.Instance(); am->UseAction(FFXIVClientStructs.FFXIV.Client.Game.ActionType.GeneralAction, 44, 0xE0000000, 0, 0, 0, null); return new { success = true }; } } });
        registry.Register(new ToolDefinition { Name = "toggle_sprint", Description = "切换冲刺", Handler = _ => { EnsureReady(); unsafe { var am = FFXIVClientStructs.FFXIV.Client.Game.ActionManager.Instance(); am->UseAction(FFXIVClientStructs.FFXIV.Client.Game.ActionType.GeneralAction, 4, 0xE0000000, 0, 0, 0, null); return new { success = true }; } } });
        registry.Register(new ToolDefinition { Name = "jump", Description = "跳跃", Handler = _ => { EnsureReady(); unsafe { var am = FFXIVClientStructs.FFXIV.Client.Game.ActionManager.Instance(); am->UseAction(FFXIVClientStructs.FFXIV.Client.Game.ActionType.GeneralAction, 2, 0xE0000000, 0, 0, 0, null); return new { success = true }; } } });
    }

    private static void EnsureReady() { if (!Service.IsReady) throw new InvalidOperationException("游戏角色未登录"); }
}
