using System.Text.Json;
using MCPforDalamud.McpServer;
using Lumina.Excel;

namespace MCPforDalamud.Tools;

public static class ExcelTools
{
    public static void Register(ToolRegistry registry)
    {
        registry.Register(new ToolDefinition { Name = "list_excel_sheets", Description = "列出可用的 Excel Sheet 名称列表", Handler = _ => { var field = Service.DataManager.GetType().GetProperty("Excel"); if (field == null) return new { count = 0, sheets = Array.Empty<string>() }; var excel = field.GetValue(Service.DataManager); if (excel == null) return new { count = 0, sheets = Array.Empty<string>() }; var m = excel.GetType().GetMethod("GetSheetNames"); if (m == null) return new { count = 0, sheets = Array.Empty<string>() }; var names = (m.Invoke(excel, null) as IEnumerable<string>)?.Take(100).ToList() ?? new List<string>(); return new { count = names.Count, sheets = names }; } });

        registry.Register(new ToolDefinition { Name = "search_excel_sheet", Description = "按名称搜索 Lumina Excel 表", InputSchema = JsonSerializer.SerializeToElement(new { type = "object", properties = new { sheetName = new { type = "string" }, filterName = new { type = "string" }, maxResults = new { type = "integer" } }, required = new[] { "sheetName" } }), Handler = args => { var sheetName = args?.GetProperty("sheetName").GetString() ?? ""; var filterName = args?.TryGetProperty("filterName", out var fn) == true ? fn.GetString() ?? "" : ""; var maxResults = args?.TryGetProperty("maxResults", out var mr) == true ? mr.GetInt32() : 10; if (string.IsNullOrEmpty(sheetName)) return new { error = "请提供 sheetName" }; var sheetType = FindSheetType(sheetName); if (sheetType == null) return new { error = string.Format("未找到 Sheet: {0}", sheetName) }; try { var getExcelSheet = Service.DataManager.GetType().GetMethod("GetExcelSheet", Type.EmptyTypes); if (getExcelSheet == null) return new { error = "GetExcelSheet 不存在" }; var sheet = getExcelSheet.MakeGenericMethod(sheetType).Invoke(Service.DataManager, null); if (sheet == null) return new { error = "Sheet为空" }; var results = new List<object>(); var enumerator = sheet.GetType().GetMethod("GetEnumerator"); if (enumerator == null) return new { error = "无法枚举Sheet" }; var enumerable = (System.Collections.IEnumerable)enumerator.Invoke(sheet, null)!; foreach (var row in enumerable) { if (row == null) continue; var rowDict = new Dictionary<string, object>(); foreach (var prop in sheetType.GetProperties()) { try { var value = prop.GetValue(row); if (value == null) continue; if (value is Lumina.Text.ReadOnly.ReadOnlySeString seStr) rowDict[prop.Name] = seStr.ToString(); else if (value is not byte[] && !value.GetType().FullName!.StartsWith("Lumina.Excel.RowRef")) rowDict[prop.Name] = value; } catch { } } if (!string.IsNullOrEmpty(filterName) && !rowDict.Values.OfType<string>().Any(v => v.Contains(filterName, StringComparison.OrdinalIgnoreCase))) continue; results.Add(rowDict); if (results.Count >= maxResults) break; } return new { sheetName, totalResults = results.Count, results }; } catch (Exception ex) { return new { error = ex.Message }; } } });

        registry.Register(new ToolDefinition { Name = "get_excel_row", Description = "获取指定 Sheet 的指定行", InputSchema = JsonSerializer.SerializeToElement(new { type = "object", properties = new { sheetName = new { type = "string" }, rowId = new { type = "integer" } }, required = new[] { "sheetName", "rowId" } }), Handler = args => { var sheetName = args?.GetProperty("sheetName").GetString() ?? ""; var rowId = (uint)(args?.GetProperty("rowId").GetInt32() ?? 0); if (string.IsNullOrEmpty(sheetName)) return new { error = "请提供 sheetName" }; var sheetType = FindSheetType(sheetName); if (sheetType == null) return new { error = string.Format("未找到 Sheet: {0}", sheetName) }; try { var getExcelSheet = Service.DataManager.GetType().GetMethod("GetExcelSheet", Type.EmptyTypes); if (getExcelSheet == null) return new { error = "GetExcelSheet不存在" }; var sheet = getExcelSheet.MakeGenericMethod(sheetType).Invoke(Service.DataManager, null); var getRow = sheet?.GetType().GetMethod("GetRow", new[] { typeof(uint) }); var row = getRow?.Invoke(sheet, new object[] { rowId }); if (row == null) return new { sheetName, rowId, found = false }; var rowDict = new Dictionary<string, object>(); foreach (var prop in sheetType.GetProperties()) { try { var val = prop.GetValue(row); if (val == null) continue; if (val is Lumina.Text.ReadOnly.ReadOnlySeString seStr) rowDict[prop.Name] = seStr.ToString(); else if (val is not byte[] && !val.GetType().FullName!.StartsWith("Lumina.Excel.RowRef")) rowDict[prop.Name] = val; } catch { } } return new { sheetName, rowId, found = true, data = rowDict }; } catch (Exception ex) { return new { error = ex.Message }; } } });
    }

    private static Type? FindSheetType(string sheetName) { foreach (var asm in AppDomain.CurrentDomain.GetAssemblies()) { try { foreach (var t in asm.GetTypes()) { var attr = t.GetCustomAttributes(typeof(SheetAttribute), false).FirstOrDefault() as SheetAttribute; if (attr != null && attr.Name == sheetName) return t; } } catch { } } return null; }
}
